# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  unless File.exist?("./custom.yaml")
    abort("Required ./custom.yaml file does not exist. Consult vagrantfiles/custom.yaml for reference.")
  end
  custom_vars = YAML.load_file("./custom.yaml")
  WD = custom_vars["wheredir"]
  global_vars = YAML.load_file("#{WD}config/global.yaml")
  if File.exist?("./secret.yaml")
    secret_vars = YAML.load_file("./secret.yaml")
  elsif File.exist?("#{WD}config/secret.yaml")
    secret_vars = YAML.load_file("#{WD}config/secret.yaml")
  else
    abort("The required ./secret.yaml or #{WD}config/secret.yaml file does not exist. Consult #{WD}config/secret_example.yaml for reference.")
  end
  lab_vars = YAML.load_file("#{WD}config/lab/suma.yaml")
  LABNAME = lab_vars["labname"]
  lab_vars["requiredsecrets"].each do |code|
    if (secret_vars[code.downcase].empty?)
      abort("Required #{code.downcase} variable has not been filled out in the secret.yaml file.")
    end
  end
  lab_vars["requiredplugins"].each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      abort("Required #{plugin.downcase} Vagrant plugin has not been loaded. See \"vagrant plugin list\" for loaded plugins.")
    end
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |libvirt, override|
    libvirt.cpus = custom_vars["libvirt"]["cpus"]
    libvirt.memory = custom_vars["libvirt"]["memory"]
    libvirt.machine_virtual_size = custom_vars["libvirt"]["machine_virtual_size"]
    libvirt.storage :file, size: "200G"
  end

  config.trigger.before :destroy do |trigger|
    trigger.name = "unregister"
    trigger.info = "unregister client"
    trigger.on_error = :continue
    trigger.only_on = lab_vars["suseconnect-d"]
    trigger.run_remote = {inline: <<-SHELL
      echo "nameserver #{custom_vars["network"]["nameserver"]}" >>/etc/resolv.conf
      if [[ $( SUSEConnect --status | python3 -c "import sys, json; print(json.load(sys.stdin)[0]['status'])" ) == "Registered" ]];
      then
        if command -v transactional-update >/dev/null 2>&1; then
          transactional-update register -d
        else
          SUSEConnect -d;
        fi
      fi
    SHELL
    }
  end

  # SUMA Client
  config.vm.define "#{LABNAME}client" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}client.yaml")
    sle.vm.box = global_vars["box"]["sle15sp7"]
    sle.vm.box_url = global_vars["boxurl"]["sle15sp7"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", hostname: true
    sle.vm.provider :libvirt do |libvirt, override|
      libvirt.cpus = 1
      libvirt.memory = 2048
    end
    sle.vm.provision "shell" do |s|
      s.name = "common"
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "SLE15"
      s.env = {
        "SLEREGCODE" => secret_vars["sleregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.provision "shell" do |s|
      s.name = "bootstrap"
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}client/bootstrap.sh"
      s.args = "#{LABNAME}client #{custom_vars["deployment"]}"
      s.env = {
        "SUBNET" => custom_vars["network"]["primarysubnet"],
      }
    end
  end

  # SUMA 5 on SLE Micro
  config.vm.define "#{LABNAME}micro" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}micro.yaml")
    sle.vm.box = global_vars["box"]["micro6"]
    sle.vm.box_url = global_vars["boxurl"]["micro6"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", type: "dhcp", auto_config: false
    if ! (custom_vars["network"]["bridgename"].empty?)
      sle.vm.network "public_network", dev: custom_vars["network"]["bridgename"], mode: "bridge", type: "bridge", auto_config: false
    end
    sle.vm.provision "shell" do |s|
      s.name = "common"
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "MICRO5"
      s.env = {
        "MICROREGCODE" => secret_vars["microregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "SUBNET" => custom_vars["network"]["primarysubnet"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.provision "shell" do |s|
      s.name = "bootstrap"
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}micro/bootstrap.sh"
      s.args = "#{LABNAME}micro #{custom_vars["deployment"]}"
      s.env = {
        "SUMAREGCODE" => secret_vars["sumaregcode"],
        "SUMAPRODUCT" => machine_vars["sumaproduct"],
        "SUBNET" => custom_vars["network"]["primarysubnet"],
      }
    end
    sle.vm.provision :reload
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}micro/mgradm.yaml", destination: "/tmp/"
    sle.vm.provision "shell" do |s|
      s.name = "bootstrap2"
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}micro/bootstrap2.sh"
      s.args = "#{LABNAME}micro #{custom_vars["deployment"]}"
      s.env = {
        "MIRRORUSER" => secret_vars["sccorguser"],
        "MIRRORPASS" => secret_vars["sccorgpass"],
      }
    end
  end

  # SUMA 5 on SLE 15
  config.vm.define "#{LABNAME}15" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}15.yaml")
    sle.vm.box = global_vars["box"]["sle15sp6"]
    sle.vm.box_url = global_vars["boxurl"]["sle15sp6"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", hostname: true
    if ! (custom_vars["network"]["bridgename"].empty?)
      sle.vm.network "public_network", dev: custom_vars["network"]["bridgename"], mode: "bridge", type: "bridge"
    end
    sle.vm.provision "shell" do |s|
      s.name = "common"
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "SLE15"
      s.env = {
        "SLEREGCODE" => secret_vars["sleregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}15/mgradm.yaml", destination: "/tmp/"
    sle.vm.provision "shell" do |s|
      s.name = "bootstrap"
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}15/bootstrap.sh"
      s.args = "#{LABNAME}15 #{custom_vars["deployment"]}"
      s.env = {
        "SUMAREGCODE" => secret_vars["sumaregcode"],
        "SUMAPRODUCT" => machine_vars["sumaproduct"],
        "SLEPRODUCT" => machine_vars["sleproduct"],
        "MIRRORUSER" => secret_vars["sccorguser"],
        "MIRRORPASS" => secret_vars["sccorgpass"],
        "SUBNET" => custom_vars["network"]["primarysubnet"],
      }
    end
  end

end
