---
suseconnect-d: ["sumaserver42", "sumaserver43", "sumaproxy42", "sumaproxy43", "sap12sp5", "sap15sp5"]
labname: "suma"
requiredsecrets: ["sleregcode", "sumaregcode", "sumaproxyregcode", "sccorguser", "sccorgpass"]

machines:  
  pre-setup43:
    - sumaserver43
    - sles15sp5
  training:
    - sumaserver42
    - client1
    - client2
    - client3
    - client4
    - major-up
  fulldeploy:
    - sumaserver43
    - sumaproxy43
    - sles15sp5
    - sles12sp5
  fulldeploy-insane: 
    - sumaserver43
    - sumaproxy43
    - sles15sp4
    - sles15sp5
    - sles12sp5
    - sap12sp5
    - sap15sp5
    - alma8
    - alma9
    - amazon2
    - centos7
    - centos8
    - debian10
    - debian11
    - oracle7
    - oracle8
    - oracle9
    - rhel7
    - rhel8
    - rhel9
    - rocky8
    - rocky9
    - ubuntu1804
    - ubuntu2004
    - ubuntu2204