box: "sle15sp3"
short: "client3"
fqdn: "client3.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".13"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"