box: "sle15sp3"
short: "client2"
fqdn: "client2.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".12"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"