box: "sle15sp3"
short: "client1"
fqdn: "client1.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".11"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"