box: "sle15sp3"
short: "client4"
fqdn: "client4.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".58"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"