box: "debian11"
short: "debian11"
fqdn: "debian11.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".60"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
static: "N"