box: "debian10"
short: "debian10"
fqdn: "debian10.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".59"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
static: "N"