box: "sle15sp3"
short: "proxy"
fqdn: "proxy.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".101"
cpus: "2"
memory: "8192"
datadisk: "100G"
provisioning: "proxy/bootstrap.sh"
environment: "SLE15"
static: "N"