box: "sle12sp5"
short: "sap12sp5"
fqdn: "sap12sp5.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".70"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE12"
static: "N"