box: "sle15sp3"
short: "server"
fqdn: "server.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".100"
public: "true"
cpus: "2"
memory: "8192"
datadisk: "200G"
provisioning: "server/bootstrap.sh"
environment: "SLE15"
static: "static1"