box: "sle15sp5"
short: "sles15sp5"
fqdn: "sles15sp5.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".74"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"