box: "sle15sp4"
short: "sles15sp4"
fqdn: "sles15sp4.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".73"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE15"
static: "N"