box: "sle15sp3"
short: "sumaproxy"
fqdn: "sumaproxy.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".75"
cpus: "2"
memory: "8192"
datadisk: "100G"
provisioning: "proxy/bootstrap.sh"
files: "proxy/files"
environment: "SLE15"
static: "N"