box: "sle15sp4"
short: "sumaproxy1"
fqdn: "sumaproxy1.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".76"
cpus: "2"
memory: "8192"
datadisk: "200G"
provisioning: "proxy/bootstrap.sh"
files: "proxy/files"
environment: "SLE15"
static: "N"