box: "sle15sp4"
short: "sumaserver1"
fqdn: "sumaserver1.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".78"
public: "true"
cpus: "4"
memory: "32768"
datadisk: "2T"
provisioning: "server/bootstrap.sh"
files: "server/files"
environment: "SLE15"
static: "static1"