box: "sle15sp3"
short: "sumaserver"
fqdn: "sumaserver.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".100"
public: "true"
cpus: "2"
memory: "8192"
datadisk: "200G"
provisioning: "server/bootstrap.sh"
files: "server/files"
environment: "SLE15"
static: "static1"