box: "ubuntu2204"
short: "ubuntu2204"
fqdn: "ubuntu2204.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".81"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
static: "N"