box: "ubuntu2004"
short: "ubuntu2004"
fqdn: "ubuntu2004.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".80"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
static: "N"