box: "ubuntu1804"
short: "ubuntu1804"
fqdn: "ubuntu1804.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".79"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
static: "N"