MANAGER_USER="spacewalk"
MANAGER_PASS="spacewalk"
MANAGER_FORCE_INSTALL='1'
ACTIVATE_SLP='n'
MANAGER_ADMIN_EMAIL='sumalabs@labs.suse.com'
MANAGER_ENABLE_TFTP='y'
MANAGER_IP="$(ip address show eth2 | grep 'inet ' | awk '{print $2}'| cut -d'/' -f1)"
MANAGER_DB_PORT='5432'
DB_BACKEND='postgresql'
MANAGER_DB_NAME='susemanager'
MANAGER_DB_PROTOCOL='TCP'
MANAGER_PASS='sumapass'
MANAGER_USER='susemanager'
LOCAL_DB='1'
CERT_CITY='Pleasant Grove'
CERT_COUNTRY='US'
CERT_EMAIL='susemanager@labs.suse.com'
CERT_O='SUSE'
CERT_OU='Support'
CERT_PASS='sumapass'
CERT_STATE='UT'
SCC_USER="$SCCORGUSER"
SCC_PASS="$SCCORGPASS"