# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  unless File.exist?("./custom.yaml")
    abort("Required ./custom.yaml file does not exist. Consult vagrantfiles/custom.yaml for reference.")
  end
  custom_vars = YAML.load_file("./custom.yaml")
  WD = custom_vars["wheredir"]
  global_vars = YAML.load_file("#{WD}config/global.yaml")
  if File.exist?("./secret.yaml")
    secret_vars = YAML.load_file("./secret.yaml")
  elsif File.exist?("#{WD}config/secret.yaml")
    secret_vars = YAML.load_file("#{WD}config/secret.yaml")
  else
    abort("The required ./secret.yaml or #{WD}config/secret.yaml file does not exist. Consult #{WD}config/secret_example.yaml for reference.")
  end
  lab_vars = YAML.load_file("#{WD}config/lab/s4hana.yaml")
  LABNAME = lab_vars["labname"]
  lab_vars["requiredsecrets"].each do |code|
    if (secret_vars[code.downcase].empty?)
      abort("Required #{code.downcase} variable has not been filled out in the secret.yaml file.")
    end
  end
  lab_vars["requiredplugins"].each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      abort("Required #{plugin.downcase} Vagrant plugin has not been loaded. See \"vagrant plugin list\" for loaded plugins.")
    end
  end
  if Dir.entries("#{WD}provisioners/lab/#{LABNAME}/sapcd/").size <= 3
    abort("The #{WD}provisioners/lab/#{LABNAME}/sapcd/ directory has not been populated with S4HANA media.")
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |libvirt, override|
    libvirt.cpus = custom_vars["libvirt"]["cpus"]
    libvirt.memory = custom_vars["libvirt"]["memory"]
    libvirt.machine_virtual_size = custom_vars["libvirt"]["machine_virtual_size"]
  end

  config.trigger.before :destroy do |trigger|
    trigger.name = "unregister"
    trigger.info = "unregister client"
    trigger.on_error = :continue
    trigger.only_on = lab_vars["suseconnect-d"]
    trigger.run_remote = {inline: <<-SHELL
      echo "nameserver #{custom_vars["network"]["nameserver"]}" >>/etc/resolv.conf
      if [[ $( SUSEConnect --status | python3 -c "import sys, json; print(json.load(sys.stdin)[0]['status'])" ) == "Registered" ]];
      then
        SUSEConnect -d;
      fi
    SHELL
    }
  end

  # ISCSI Server
  config.vm.define "#{LABNAME}iscsi" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}iscsi.yaml")
    n1_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}01.yaml")
    n2_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}02.yaml")
    sle.vm.box = global_vars["box"]["sle15sp7"]
    sle.vm.box_url = global_vars["boxurl"]["sle15sp7"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", hostname: true
    sle.vm.provider :libvirt do |libvirt, override|
      libvirt.cpus = 2
      libvirt.machine_virtual_size = 40
    end
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "SLE15"
      s.env = {
        "SLEREGCODE" => secret_vars["sleregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.synced_folder "#{WD}provisioners/lab/#{LABNAME}/sapcd/", "/opt/", type: "rsync"
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}iscsi/bootstrap.sh"
      s.args = "#{LABNAME}iscsi #{custom_vars["deployment"]}"
      s.env = {
        "SUBNET" => custom_vars["network"]["primarysubnet"],
        "N1IP" => n1_vars["ipaddress"],
        "N2IP" => n2_vars["ipaddress"]
      }
    end
  end

  # HA15 Cluster Node 1
  config.vm.define "#{LABNAME}01" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}01.yaml")
    iscsi_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}iscsi.yaml")
    n2_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}02.yaml")
    sle.vm.box = global_vars["box"]["sle15sp7"]
    sle.vm.box_url = global_vars["boxurl"]["sle15sp7"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", hostname: true
    if ! (custom_vars["network"]["bridgename"].empty?)
      sle.vm.network "public_network", dev: custom_vars["network"]["bridgename"], mode: "bridge", type: "bridge"
    end
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "SLE15"
      s.env = {
        "SLEREGCODE" => secret_vars["sleregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.synced_folder "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/ascs", "/tmp/ascs/", type: "rsync"
    sle.vm.synced_folder "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/ers", "/tmp/ers/", type: "rsync"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/crm_part1.txt", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/crm_part2.txt", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/crm_part3.txt", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/authorized_keys", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/id_rsa", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/id_rsa.pub", destination: "/tmp/"
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}01/bootstrap.sh"
      s.args = "#{LABNAME}01 #{custom_vars["deployment"]}"
      s.env = {
        "SAPREGCODE" => secret_vars["sapregcode"],
        "SAPPRODUCT" => machine_vars["sapproduct"],
        "FLOATINGIP1" => "#{custom_vars["network"]["primarysubnet"]}#{lab_vars["floatingip1"]}", 
        "FLOATINGIP2" => "#{custom_vars["network"]["primarysubnet"]}#{lab_vars["floatingip2"]}", 
        "SUBNET" => custom_vars["network"]["primarysubnet"],
        "ISCSIIP" => iscsi_vars["ipaddress"],
        "N2IP" => n2_vars["ipaddress"]
      }
    end
  end

  # HA15 Cluster Node 2
  config.vm.define "#{LABNAME}02" do |sle|
    machine_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}02.yaml")
    iscsi_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}iscsi.yaml")
    n1_vars = YAML.load_file("#{WD}config/machines/#{LABNAME}/#{LABNAME}01.yaml")
    sle.vm.box = global_vars["box"]["sle15sp7"]
    sle.vm.box_url = global_vars["boxurl"]["sle15sp7"]
    sle.vm.hostname = machine_vars["fqdn"]
    sle.vm.network "private_network", ip: "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}", hostname: true
    if ! (custom_vars["network"]["bridgename"].empty?)
      sle.vm.network "public_network", dev: custom_vars["network"]["bridgename"], mode: "bridge", type: "bridge"
    end
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/common/bootstrap.sh"
      s.args = "SLE15"
      s.env = {
        "SLEREGCODE" => secret_vars["sleregcode"],
        "IPADDRESS" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ipaddress"]}",
        "FQDN" => machine_vars["fqdn"],
        "SHORT" => machine_vars["short"],
        "NTPSERVER" => "#{custom_vars["network"]["primarysubnet"]}#{machine_vars["ntpserver"]}"
      }
    end
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}02/authorized_keys", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}02/id_rsa", destination: "/tmp/"
    sle.vm.provision "file", source: "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}02/id_rsa.pub", destination: "/tmp/"
    sle.vm.provision "shell" do |s|
      s.path = "#{WD}provisioners/lab/#{LABNAME}/#{LABNAME}02/bootstrap.sh"
      s.args = "#{LABNAME}02 #{custom_vars["deployment"]}"
      s.env = {
        "SAPREGCODE" => secret_vars["sapregcode"],
        "SAPPRODUCT" => machine_vars["sapproduct"],
        "FLOATINGIP1" => "#{custom_vars["network"]["primarysubnet"]}#{lab_vars["floatingip1"]}", 
        "FLOATINGIP2" => "#{custom_vars["network"]["primarysubnet"]}#{lab_vars["floatingip2"]}", 
        "SUBNET" => custom_vars["network"]["primarysubnet"],
        "ISCSIIP" => iscsi_vars["ipaddress"],
        "N1IP" => n1_vars["ipaddress"]
      }
    end
  end
end

